### ISSUE TITLE
Create service class to interact with the API

### ISSUE THREAD

**Issue by peter-gy** [memoriesadrift/we-find#14]
The service class should expose the following functionalities:
- Exact and non-fuzzy search for courses
- Search for courses marked with a certain label
- Search for courses of a certain directorate of studies
- Search for courses of certain course types
- Search for courses in certain semesters

**Comment by peter-gy** [comment]
@michalrzak, @memoriesadrift you are more involved with the UI right now. Do you think that these functionalities will be sufficient for you?

Any search feature listed [on the help page of u:find](https://ufind.univie.ac.at/en/help.html) can be implemented.

**Comment by memoriesadrift** [comment]
For the Course Directory, we will need to get data for Degree Programmes, Modules and Course Groups -> see trying to navigate to e.g. Modellierung in from the VVZ page - is that possible with the things you mentioned? If yes, imo all good

**Comment by peter-gy** [comment]
Closed by  #35
