### ISSUE TITLE
Implement full multilingual support

### ISSUE THREAD

**Issue by memoriesadrift** [memoriesadrift/we-find#25]
Many parts of the app do not handle multilinguality correctly, we need to implement this,

**Comment by peter-gy** [comment]
A straightforward way to do this would be to manage a single instance of the `Lang` enum (see [I18NString.dart](https://github.com/memoriesadrift/we-find/blob/main/lib/model/I18NString.dart#L19)) as a shared state (using a provider), access it in every widget and use it as the parameter of `I18NString.get`.

Spawns #33
