### ISSUE TITLE
Create Search Result Page

### ISSUE THREAD

**Issue by memoriesadrift** [memoriesadrift/we-find#3]
Create a `Scaffold` for the search result screen in `search.dart` (or a different, appropriate file name with a `Scaffold` component that holds the following, corresponding to the prototypes.

1. A search bar with a text equal to the query passed via the ctor
2. A list of results matching the query

List items should be tappable - redirect to blank screen for now.

**Comment by michalrzak** [comment]
I may end up implementing it a little different, but that should be fine (and more in line with the other screens I did).
