### ISSUE TITLE
Set up providers to manage shared state

### ISSUE THREAD

**Issue by peter-gy** [memoriesadrift/we-find#33]
Providers should be set up to manage shared state across screens and widgets. The following states should be tracked:

- [x] current language (`Lang` enum instance)
- [x] courses marked as favourite (List of `Course` instances)

**Comment by peter-gy** [comment]
@michalrzak, @memoriesadrift any other states we should keep track of and not listed in the issue?

**Comment by michalrzak** [comment]
Looks good I can't think of anything else for now, so there probably is nothing too important we are missing.
