### ISSUE TITLE
Create Course Detail Page

### ISSUE THREAD

**Issue by memoriesadrift** [memoriesadrift/we-find#4]
Create a `Scaffold` for the course detail page which will handle the specific course.
It should look similar to u:find, inspired by the prototype.
Should contain:

1. Course Name
2. ECTS Weight, SWS, etc.
3. Next course / exam date
4. Course description, groups, etc.
5. A BACK BUTTON

**Comment by michalrzak** [comment]
I think the back button will come implicitly from the navigator
