### ISSUE TITLE
Make the Search Result show more information 

### ISSUE THREAD

**Issue by michalrzak** [memoriesadrift/we-find#45]
Right now the search result only show the course name.
It would be nice if it would also show:
 * the semester of the course
 * the type of course (VU, VO, etc.)
 * Study program under which the course belongs (this may contain too much information and turns out to be too long to display)
 * ECTS (not so necessary imo, but if we have the space for it, nice to have)

**Comment by memoriesadrift** [comment]
Study Programme and Semester seems a bit too long to display. Pull #60 and see for yourself how it looks with type + ECTS.
We would have to make it two rows or something, but that just bloats hard with courses that have long names.
